### YamlMime:ManagedReference
items:
- uid: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings
  commentId: T:UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings
  id: GameStartUp.LoadingSettings
  parent: UndyneFight_Ex.GameInterface
  children:
  - UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleCentrePosition
  - UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleTextureRoot
  langs:
  - csharp
  - vb
  name: GameStartUp.LoadingSettings
  nameWithType: GameStartUp.LoadingSettings
  fullName: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings
  type: Class
  assemblies:
  - UndyneFight-Ex
  namespace: UndyneFight_Ex.GameInterface
  summary: User defined loading screen settings
  example: []
  syntax:
    content: public static class GameStartUp.LoadingSettings
    content.vb: Public Module GameStartUp.LoadingSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleCentrePosition
  commentId: P:UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleCentrePosition
  id: TitleCentrePosition
  parent: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings
  langs:
  - csharp
  - vb
  name: TitleCentrePosition
  nameWithType: GameStartUp.LoadingSettings.TitleCentrePosition
  fullName: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleCentrePosition
  type: Property
  assemblies:
  - UndyneFight-Ex
  namespace: UndyneFight_Ex.GameInterface
  summary: The position of the game logo
  example: []
  syntax:
    content: public static Vector2 TitleCentrePosition { set; }
    parameters: []
    return:
      type: Microsoft.Xna.Framework.Vector2
    content.vb: Public Shared WriteOnly Property TitleCentrePosition As Vector2
  overload: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleCentrePosition*
- uid: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleTextureRoot
  commentId: P:UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleTextureRoot
  id: TitleTextureRoot
  parent: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings
  langs:
  - csharp
  - vb
  name: TitleTextureRoot
  nameWithType: GameStartUp.LoadingSettings.TitleTextureRoot
  fullName: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleTextureRoot
  type: Property
  assemblies:
  - UndyneFight-Ex
  namespace: UndyneFight_Ex.GameInterface
  summary: The file path to the game logo sprite
  example: []
  syntax:
    content: public static string TitleTextureRoot { set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared WriteOnly Property TitleTextureRoot As String
  overload: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleTextureRoot*
references:
- uid: UndyneFight_Ex.GameInterface
  commentId: N:UndyneFight_Ex.GameInterface
  isExternal: true
  href: UndyneFight_Ex.html
  name: UndyneFight_Ex.GameInterface
  nameWithType: UndyneFight_Ex.GameInterface
  fullName: UndyneFight_Ex.GameInterface
  spec.csharp:
  - uid: UndyneFight_Ex
    name: UndyneFight_Ex
    isExternal: true
    href: UndyneFight_Ex.html
  - name: .
  - uid: UndyneFight_Ex.GameInterface
    name: GameInterface
    isExternal: true
    href: UndyneFight_Ex.GameInterface.html
  spec.vb:
  - uid: UndyneFight_Ex
    name: UndyneFight_Ex
    isExternal: true
    href: UndyneFight_Ex.html
  - name: .
  - uid: UndyneFight_Ex.GameInterface
    name: GameInterface
    isExternal: true
    href: UndyneFight_Ex.GameInterface.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleCentrePosition*
  commentId: Overload:UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleCentrePosition
  isExternal: true
  href: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.html#UndyneFight_Ex_GameInterface_GameStartUp_LoadingSettings_TitleCentrePosition
  name: TitleCentrePosition
  nameWithType: GameStartUp.LoadingSettings.TitleCentrePosition
  fullName: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleCentrePosition
- uid: Microsoft.Xna.Framework.Vector2
  commentId: T:Microsoft.Xna.Framework.Vector2
  parent: Microsoft.Xna.Framework
  isExternal: true
  name: Vector2
  nameWithType: Vector2
  fullName: Microsoft.Xna.Framework.Vector2
- uid: Microsoft.Xna.Framework
  commentId: N:Microsoft.Xna.Framework
  isExternal: true
  name: Microsoft.Xna.Framework
  nameWithType: Microsoft.Xna.Framework
  fullName: Microsoft.Xna.Framework
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Xna
    name: Xna
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework
    name: Framework
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Xna
    name: Xna
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework
    name: Framework
    isExternal: true
- uid: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleTextureRoot*
  commentId: Overload:UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleTextureRoot
  isExternal: true
  href: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.html#UndyneFight_Ex_GameInterface_GameStartUp_LoadingSettings_TitleTextureRoot
  name: TitleTextureRoot
  nameWithType: GameStartUp.LoadingSettings.TitleTextureRoot
  fullName: UndyneFight_Ex.GameInterface.GameStartUp.LoadingSettings.TitleTextureRoot
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
